esphome:
  name: "heating-control"
  friendly_name: Heating Control
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: esp32-s2-saola-1
  framework:
    type: esp-idf


# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .local  # optional: default is .local
  use_address: heating_control.local  # optional override
  
i2c:
  sda: GPIO33
  scl: GPIO35
  scan: true
  
 

sensor:
  - platform: bmp280_i2c
    address: 0x76
    temperature:
      name: "Temperature"
      id: This_Temperature
    pressure:
      name: "Pressure"
      id: This_Pressure
    
    update_interval: 60s
  - platform: homeassistant
    id: house_temperature
    entity_id: sensor.q_thermometer_1_temperature
    name: "House Temperature"
    

switch:
  - platform: gpio
    name: "RED Switch"
    pin: 
      number: GPIO07
      inverted: true
    id: red_led

  - platform: gpio
    name: "Relay 1"
    pin: 
      number: GPIO05
      inverted: true
    id: relay_1
  - platform: gpio
    name: "Relay 2"
    pin: 
      number: GPIO03
      inverted: true
    id: relay_2

# Climate Control Configuration
climate:
  - platform: thermostat
    name: "ESP32 Climate Control"
    sensor: house_temperature  # Use the BMP280 temperature sensor
    min_cooling_off_time: 5s
    min_cooling_run_time: 5s
    min_heating_off_time: 3s
    min_heating_run_time: 3s
    min_idle_time: 3s
    # Control the relays based on temperature
    heat_action:
      - switch.turn_on: relay_1  # Turn on Relay 1 for heating
    cool_action:
      - switch.turn_on: relay_2  # Turn on Relay 2 for cooling
    idle_action:
      - switch.turn_off: relay_1  # Turn off Relay 1 when idle
      - switch.turn_off: relay_2  # Turn off Relay 2 when idle
    preset:
      - name: Home
        default_target_temperature_low: 20 °C
        default_target_temperature_high: 22 °C
