# Watdog controller
# sits next to main HA host (Raspberry Pi)
# watches HA function and indicates on front rgb led

esphome:
  name: "q-watchdog"
  friendly_name: Watchdog
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: esp32-s2-saola-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  on_client_connected:
    - light.turn_on:
        id: led1
        red: 0%
        green: 00%
        blue: 100%
        brightness: 75%
        
  on_client_disconnected:
    - light.turn_on:
        id: led1
        red: 100%
        green: 0%
        blue: 0%
        brightness: 75%
        
# Allow Over-The-Air updates
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Wifi-Esp4"
    password: "password"
  on_connect:
    
    - light.turn_on: 
            id: led1
            blue: 0%
            red: 0%
            green: 100%
            brightness: 75%
           
  on_disconnect:
    - light.turn_on: 
            id: led1
            blue: 0%
            red: 100%
            green: 0%
            brightness: 75%
           


output:
  - platform: ledc
    id: red_output
    pin: GPIO07
    max_power: 75%
    inverted: True
    
  - platform: ledc
    id: green_output
    pin: GPIO05
    max_power: 75%
    inverted: True
    
  - platform: ledc
    id: blue_output
    pin: GPIO09
    max_power: 75%
    inverted: True
    

light:
  - platform: rgb
    id: led1
    name: "RGB LED"
    red: red_output
    green: green_output
    blue: blue_output
    

binary_sensor:
  - platform: status
    name: Connection Status
    id: watchdog_connection_status

interval:
  - interval: 30s
    then:
      - if:
          condition:
            binary_sensor.is_on: watchdog_connection_status
          then:
            - light.turn_on:
                id: led1
                red: 60%
                green: 00%
                blue: 100%
                brightness: 25%
               
          else:
            - light.turn_on:
                id: led1
                red: 100%
                green: 0%
                blue: 0%
                brightness: 75%
               
